### ISSUE TITLE
Clicking on Bubble takes to blank white page

### ISSUE THREAD

**Issue by jareddunne** [readysetawesome/timely-tasker#28]
Steps to Reproduce:
1) visit https://timely-tasker.com/timer
2) enter email
3) retrieve code from email and paste back into browser
4) enter a label for a row
5) click a bubble

Expected result:
Bubble is filled in and user remains on page

Actual result:
Page is replaced by a white acreen

![Screenshot_20230317-145427_Settings](https://user-images.githubusercontent.com/1776522/226060423-1715d549-6806-45ab-9966-c511fb0fe4c7.jpg)
![Screenshot_20230317-144856_Chrome](https://user-images.githubusercontent.com/1776522/226060427-a03788c6-7268-4271-ab73-afae1fa73f0d.jpg)
![Screenshot_20230317-145538_Chrome](https://user-images.githubusercontent.com/1776522/226060428-ae1168ec-a936-4d9d-9225-629860213176.jpg)

**Comment by jareddunne** [comment]
The behavior has changed. Now instead of going to white page after click on bubble it changes it's border color briefly when click when returns to original state after click. Bubble does not get filled.

**Comment by readysetawesome** [comment]
I think it’s related to single use code login, I was able to reproduce it that way

the changing behavior could be from randomness in the timing of events preceding the exception

**Comment by readysetawesome** [comment]
I think it’s better

**Comment by jareddunne** [comment]
Ya working now!
