### ISSUE TITLE
Partial bubble does not become whole when other partial bubbles unfilled

### ISSUE THREAD

**Issue by jareddunne** [readysetawesome/timely-tasker#67]
For the point of this issue I'm referring to a "partial" bubble as when there are multiple rows in the same time column that have been filled, which causes those bubbles to be indicated as a bubble with a / marking in it.

On the same Android device, as #28, I'm experiencing the following behavior.

Steps to reproduce:
1. Fill a bubble at 11:15am on task row 1 
2. Fill a bubble at 11:15am on task row 2
3. Click the partial bubble 11:15 am on task row 1.

Expected results:
After step 1: 1115am task row 1 bubble completely filled
After step 2: both 1115am bubbles on task row 1 and task row 2 are replaced with partial / slash bubbles.
After step 3: 1115am bubbles on task row 1 updates to become unfilled, while 1115am bubbles on task row 2 is updated to become totally filled (since it now the only 1115 left filled in the time column)

Actual results:
After step 1: 1115am task row 1 bubble completely filled
After step 2: both 1115am bubbles on task row 1 and task row 2 are replaced with partial / slash bubbles.
**After step 3: 1115am bubbles on task row 1 updates to become unfilled, while 1115am bubbles on task row 2 *remains a partial bubble despite being last ticked bubble in that time column*

Workaround:
Unticking and reticking 1115 bubble for task 2 will work around this issue but is not as convenient.

**Comment by readysetawesome** [comment]
i love this, makes sense.  I'll build a cypress text example first!  YAY TDD!
